### ISSUE TITLE
[12.0 -> 13.0] [base] Error while updating base module.

### ISSUE THREAD

**Issue by mojtabaakbarpour** [OCA/OpenUpgrade#2296]
Hi
When migrate base module from 12.0 to 13.0 get this error.

```
2020-04-13 04:37:29,384 6036 ERROR odoo12 OpenUpgrade: base: error in migration script base\migrations\13.0.1.3\pre-migration.py: _change_foreign_key_refs() missing 1 required positional argument: 'model_table' 
2020-04-13 04:37:29,384 6036 ERROR odoo12 OpenUpgrade: _change_foreign_key_refs() missing 1 required positional argument: 'model_table' 
Traceback (most recent call last):
  File "\venv\lib\site-packages\openupgradelib\openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "\OpenUpgrade\odoo\addons\base\migrations\13.0.1.3\pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "\OpenUpgrade\odoo\addons\base\migrations\13.0.1.3\pre-migration.py", line 719, in rename_ir_module_category
    method="sql", model_table="ir_module_category")
  File "\venv\lib\site-packages\openupgradelib\openupgrade_merge_records.py", line 556, in merge_records
    _change_foreign_key_refs(*args3)
TypeError: _change_foreign_key_refs() missing 1 required positional argument: 'model_table'
```

**Comment by pedrobaeza** [comment]
Fixed in OCA/openupgradelib@7e3a442

**Comment by mojtabaakbarpour** [comment]
@pedrobaeza 
thanks, thats problem fixed. but now i get this error:

```
2020-04-13 10:44:45,619 12624 ERROR odoo12 OpenUpgrade: base: error in migration script base\migrations\13.0.1.3\pre-migration.py: 'base' 
2020-04-13 10:44:45,619 12624 ERROR odoo12 OpenUpgrade: 'base' 
Traceback (most recent call last):
  File "\venv\lib\site-packages\openupgradelib\openupgrade.py", line 1778, in wrapped_function
    if use_env2 else cr, version)
  File "\OpenUpgrade\odoo\addons\base\migrations\13.0.1.3\pre-migration.py", line 750, in migrate
    rename_ir_module_category(env)
  File "\OpenUpgrade\odoo\addons\base\migrations\13.0.1.3\pre-migration.py", line 719, in rename_ir_module_category
    method="sql", model_table="ir_module_category")
  File "\venv\lib\site-packages\openupgradelib\openupgrade_merge_records.py", line 556, in merge_records
    _change_foreign_key_refs(*args3)
  File "\venv\lib\site-packages\openupgradelib\openupgrade_merge_records.py", line 41, in _change_foreign_key_refs
    with env.cr.savepoint():
  File "\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "\OpenUpgrade\odoo\sql_db.py", line 427, in savepoint
    flush_env(self)
  File "\OpenUpgrade\odoo\sql_db.py", line 67, in flush_env
    env['base'].flush()
  File "\OpenUpgrade\odoo\api.py", line 463, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "\OpenUpgrade\odoo\modules\registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'base'
2020-04-13 10:44:45,627 12624 WARNING odoo12 odoo.modules.loading: Transient module states were reset 
2020-04-13 10:44:45,628 12624 ERROR odoo12 odoo.modules.registry: Failed to load registry 
```
