### ISSUE TITLE
[9.0] ImportError: cannot import name ProtocolError

### ISSUE THREAD

**Issue by guile520** [OCA/OpenUpgrade#982]
Impacted versions: 9.0

Steps to reproduce: trying to migrate an odoo v8.0 database with standard modules installed, or a clean v8.0 new database to v9.0

Current behavior: i get this error in the shell : 

copying database migrate_test to migrate_test_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 9.0
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp-server", line 2, in <module>
    import openerp
  File "/var/tmp/openupgrade/9.0/server/openerp/__init__.py", line 86, in <module>
    import cli
  File "/var/tmp/openupgrade/9.0/server/openerp/cli/__init__.py", line 9, in <module>
    import deploy
  File "/var/tmp/openupgrade/9.0/server/openerp/cli/deploy.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 22, in <module>
    from .packages.urllib3.exceptions import (
ImportError: cannot import name ProtocolError

I don't understand this error, and couldn't find any solution. (pip installing urllib3 didn't work)
I've already used this script to migrate a new database with some modules installed (standard ones) from openerp v7.0 to odoo v8.0 on another server, with no issue.

Expected behavior: this script should work on a fresh install centos 7.0/webmin/postgresql.

**Comment by pedrobaeza** [comment]
It's a problem with your OS. You should use Python 2.7.

**Comment by guile520** [comment]
thanks a lot for time saved.
