### ISSUE TITLE
Title: hr_org_chart AttributeError during 18→19 migration when employee write_date is NULL      OpenUpgrade version: 19.0

### ISSUE THREAD

**Issue by tate11** [OCA/OpenUpgrade#5621]
Description:

    After migrating an Odoo database from 18.0 to 19.0 using OpenUpgrade, clicking on an employee triggers the org chart endpoint and produces:
    AttributeError: 'bool' object has no attribute 'timestamp'

    The error is in odoo/addons/hr_org_chart/controllers/hr_org_chart.py:35:
    python
    write_date=int(employee.write_date.timestamp()) * 1000,

    When employee.write_date is False (NULL in DB), .timestamp() fails. This is likely to affect migrated databases where some employee records may have empty write_date.
    Workaround applied during migration: patch the controller to check for falsy write_date:
    python
    write_date=int(employee.write_date.timestamp() * 1000) if employee.write_date else 0,

**Comment by pedrobaeza** [comment]
Did you migrate before merging #5605 ?

**Comment by tate11** [comment]
#5605 adds contract_date_start to hr_version INSERT. It doesn't affect hr.employee.write_date at all. The error here is from pre-existing NULL write_date on
     hr.employee records in the source DB — a data quality issue, not an OpenUpgrade migration bug. #5605 wouldn't prevent this crash

**Comment by pedrobaeza** [comment]
And why your DB contains that NULL values? The ORM writes both create* and write* fields on creation, so it seems a problem on your specific DB.

**Comment by tate11** [comment]
> And why your DB contains that NULL values? The ORM writes both create* and write* fields on creation, so it seems a problem on your specific DB.

 We've observed this error on multiple databases during our 18→19 migrations. The admin user's employee record has write_date set, so the admin doesn't see the crash. We need to verify where exactly
     these NULL values come from in the source data. Could this be related to how the ORM handles employee creation during module installation/upgrade in previous versions? We'll investigate further on our
     end and report back.

**Comment by dnplkndll** [comment]
Upstream fix proposed against Odoo: https://github.com/odoo/odoo/pull/264591 — adds the same defensive guard on \`employee.write_date\` that \`base/models/avatar_mixin.py:67\` already uses for \`create_date\`.

Audited \`addons/hr_org_chart/\` end-to-end: \`controllers/hr_org_chart.py:35\` is the only place that crashes on NULL \`write_date\`. \`_prepare_employee_data\` is the single funnel for \`get_org_chart\`, \`get_subordinates\`, and the rest of the controller endpoints, and the XML templates (\`static/src/fields/hr_org_chart.xml:27,163\`) just consume whatever the controller returns — they tolerate \`0\` as the cache-bust value.

So that one-line change is complete coverage for the NULL case in this module.

**Comment by tate11** [comment]
Big thanks to @dnplkndll for submitting the upstream fix at odoo/odoo#264591 — it has been merged into Odoo 19.0 (commit 30899084af6f028c68b3bba2a07c697755bfaf09). The fix is the same defensive guard described here. Since this is an Odoo core issue and the fix is already in the 19.0 branch, this is no longer an OpenUpgrade concern. Closing as resolved upstream. Thanks again @dnplkndll
